# Generated by Django 4.2.20 on 2026-05-10 02:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Reporte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=120, verbose_name='Título')),
                ('descripcion', models.TextField(verbose_name='Descripción')),
                ('categoria', models.CharField(choices=[('residuos_solidos', 'Residuos Sólidos'), ('escombros', 'Escombros'), ('residuos_peligrosos', 'Residuos Peligrosos'), ('raee', 'RAEE (Electrónicos)'), ('organicos', 'Orgánicos'), ('otro', 'Otro')], db_index=True, max_length=30, verbose_name='Categoría')),
                ('latitud', models.FloatField(verbose_name='Latitud')),
                ('longitud', models.FloatField(verbose_name='Longitud')),
                ('foto', models.ImageField(upload_to='reportes/', verbose_name='Foto')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('en_gestion', 'En Gestión'), ('resuelto', 'Resuelto'), ('rechazado', 'Rechazado')], db_index=True, default='pendiente', max_length=20, verbose_name='Estado')),
                ('municipio', models.CharField(choices=[('Chia', 'Chía'), ('Cajica', 'Cajicá'), ('Zipaquira', 'Zipaquirá'), ('Cogua', 'Cogua'), ('Tausa', 'Tausa'), ('Sopo', 'Sopó'), ('Tocancipa', 'Tocancipá'), ('Gachancipa', 'Gachancipá'), ('Nemocon', 'Nemocón'), ('Supata', 'Supatá'), ('Tabio', 'Tabio')], db_index=True, max_length=50, verbose_name='Municipio')),
                ('nota_operador', models.TextField(blank=True, null=True, verbose_name='Nota del operador')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('operador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reportes_gestionados', to=settings.AUTH_USER_MODEL, verbose_name='Operador asignado')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reportes', to=settings.AUTH_USER_MODEL, verbose_name='Ciudadano')),
            ],
            options={
                'verbose_name': 'Reporte',
                'verbose_name_plural': 'Reportes',
                'ordering': ['-created_at'],
            },
        ),
    ]
