# Generated by Django 4.2.20 on 2026-05-10 02:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroResiduo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semana', models.DateField(help_text='Fecha del lunes de la semana registrada', verbose_name='Semana (lunes)')),
                ('municipio', models.CharField(choices=[('Chia', 'Chía'), ('Cajica', 'Cajicá'), ('Zipaquira', 'Zipaquirá'), ('Cogua', 'Cogua'), ('Tausa', 'Tausa'), ('Sopo', 'Sopó'), ('Tocancipa', 'Tocancipá'), ('Gachancipa', 'Gachancipá'), ('Nemocon', 'Nemocón'), ('Supata', 'Supatá'), ('Tabio', 'Tabio')], db_index=True, max_length=50, verbose_name='Municipio')),
                ('organico_kg', models.FloatField(default=0, verbose_name='Orgánico (kg)')),
                ('reciclable_kg', models.FloatField(default=0, verbose_name='Reciclable (kg)')),
                ('no_reciclable_kg', models.FloatField(default=0, verbose_name='No reciclable (kg)')),
                ('especial_kg', models.FloatField(default=0, verbose_name='Especial (kg)')),
                ('peligroso_kg', models.FloatField(default=0, verbose_name='Peligroso (kg)')),
                ('observaciones', models.TextField(blank=True, null=True, verbose_name='Observaciones')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registros_residuos', to=settings.AUTH_USER_MODEL, verbose_name='Ciudadano')),
            ],
            options={
                'verbose_name': 'Registro de Residuos',
                'verbose_name_plural': 'Registros de Residuos',
                'ordering': ['-semana'],
                'unique_together': {('usuario', 'semana')},
            },
        ),
    ]
