# Generated by Django 4.2.20 on 2026-05-10 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('residuos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='registroresiduo',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
